name: Deploy to Firebase
on:
  release:
    types: [published]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@master
      - name: Setup Node.js Environment
        uses: actions/setup-node@master
        with:
          node_version: '12.x'
      - name: Install Node Dependencies
        run: npm run install:ci
      - name: Install Firebase CLI
        run: npm install -d firebase-tools
      - name: Build Project for Production
        run: npm run build:prod
      - name: Deploy to Firebase
        run: npx firebase deploy --force
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        
