name: Continuous Integration
on:
  pull_request:
    branches: [main]
jobs:
  integrate:
    name: Build and Test Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@master
      - name: Setup Node.js Environment
        uses: actions/setup-node@master
        with:
          node_version: '12.x'
      - name: Install Project Dependencies
        run: npm run install:ci
      - name: Run Unit Tests
        run: npm run test:ci
      - name: Check Build
        run: npm run build:prod
